# Goal tolerance parameters
xy_goal_tolerance: 0.05  # 5cm position tolerance
yaw_goal_tolerance: 0.087  # ~5 degrees orientation tolerance
latch_xy_goal_tolerance: true  # CRITICAL: This prevents the wiggling behavior

# DWA Local Planner parameters (if using DWA)
DWAPlannerROS:
  # Angular velocity and acceleration limits - REDUCE these to prevent overshoot
  max_vel_theta: 0.8  # Reduced from default ~1.5
  min_vel_theta: 0.1
  acc_lim_theta: 1.0  # Reduced from default ~3.2
  
  # Goal tolerance (should match global settings)
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.087
  latch_xy_goal_tolerance: true
  
  # Rotation behavior
  min_in_place_vel_theta: 0.4  # Minimum rotation speed
  rot_stopped_vel: 0.01
  
  # Oscillation prevention
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2

# OR if using TrajectoryPlannerROS:
TrajectoryPlannerROS:
  max_vel_theta: 0.8
  min_vel_theta: 0.1
  min_in_place_vel_theta: 0.4
  acc_lim_theta: 1.0
  
  xy_goal_tolerance: 0.05
  yaw_goal_tolerance: 0.087
  latch_xy_goal_tolerance: true