// Generated by gencpp from file apriltag_finder/ApriltagsIDsSrv.msg
// DO NOT EDIT!


#ifndef APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRV_H
#define APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRV_H

#include <ros/service_traits.h>


#include <apriltag_finder/ApriltagsIDsSrvRequest.h>
#include <apriltag_finder/ApriltagsIDsSrvResponse.h>


namespace apriltag_finder
{

struct ApriltagsIDsSrv
{

typedef ApriltagsIDsSrvRequest Request;
typedef ApriltagsIDsSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ApriltagsIDsSrv
} // namespace apriltag_finder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::apriltag_finder::ApriltagsIDsSrv > {
  static const char* value()
  {
    return "4f22efebf407aadba2ecc69df353d113";
  }

  static const char* value(const ::apriltag_finder::ApriltagsIDsSrv&) { return value(); }
};

template<>
struct DataType< ::apriltag_finder::ApriltagsIDsSrv > {
  static const char* value()
  {
    return "apriltag_finder/ApriltagsIDsSrv";
  }

  static const char* value(const ::apriltag_finder::ApriltagsIDsSrv&) { return value(); }
};


// service_traits::MD5Sum< ::apriltag_finder::ApriltagsIDsSrvRequest> should match
// service_traits::MD5Sum< ::apriltag_finder::ApriltagsIDsSrv >
template<>
struct MD5Sum< ::apriltag_finder::ApriltagsIDsSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::apriltag_finder::ApriltagsIDsSrv >::value();
  }
  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::apriltag_finder::ApriltagsIDsSrvRequest> should match
// service_traits::DataType< ::apriltag_finder::ApriltagsIDsSrv >
template<>
struct DataType< ::apriltag_finder::ApriltagsIDsSrvRequest>
{
  static const char* value()
  {
    return DataType< ::apriltag_finder::ApriltagsIDsSrv >::value();
  }
  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::apriltag_finder::ApriltagsIDsSrvResponse> should match
// service_traits::MD5Sum< ::apriltag_finder::ApriltagsIDsSrv >
template<>
struct MD5Sum< ::apriltag_finder::ApriltagsIDsSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::apriltag_finder::ApriltagsIDsSrv >::value();
  }
  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::apriltag_finder::ApriltagsIDsSrvResponse> should match
// service_traits::DataType< ::apriltag_finder::ApriltagsIDsSrv >
template<>
struct DataType< ::apriltag_finder::ApriltagsIDsSrvResponse>
{
  static const char* value()
  {
    return DataType< ::apriltag_finder::ApriltagsIDsSrv >::value();
  }
  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRV_H
