// Generated by gencpp from file apriltag_finder/ApriltagsIDsSrvResponse.msg
// DO NOT EDIT!


#ifndef APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRVRESPONSE_H
#define APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRVRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apriltag_finder
{
template <class ContainerAllocator>
struct ApriltagsIDsSrvResponse_
{
  typedef ApriltagsIDsSrvResponse_<ContainerAllocator> Type;

  ApriltagsIDsSrvResponse_()
    : ids()  {
    }
  ApriltagsIDsSrvResponse_(const ContainerAllocator& _alloc)
    : ids(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _ids_type;
  _ids_type ids;





  typedef boost::shared_ptr< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ApriltagsIDsSrvResponse_

typedef ::apriltag_finder::ApriltagsIDsSrvResponse_<std::allocator<void> > ApriltagsIDsSrvResponse;

typedef boost::shared_ptr< ::apriltag_finder::ApriltagsIDsSrvResponse > ApriltagsIDsSrvResponsePtr;
typedef boost::shared_ptr< ::apriltag_finder::ApriltagsIDsSrvResponse const> ApriltagsIDsSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator1> & lhs, const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ids == rhs.ids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator1> & lhs, const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace apriltag_finder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f22efebf407aadba2ecc69df353d113";
  }

  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f22efebf407aadbULL;
  static const uint64_t static_value2 = 0xa2ecc69df353d113ULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apriltag_finder/ApriltagsIDsSrvResponse";
  }

  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Response\n"
"int32[] ids\n"
"\n"
;
  }

  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ApriltagsIDsSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::apriltag_finder::ApriltagsIDsSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "ids[]" << std::endl;
    for (size_t i = 0; i < v.ids.size(); ++i)
    {
      s << indent << "  ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRVRESPONSE_H
