// Generated by gencpp from file apriltag_finder/ApriltagsIDsSrvRequest.msg
// DO NOT EDIT!


#ifndef APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRVREQUEST_H
#define APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace apriltag_finder
{
template <class ContainerAllocator>
struct ApriltagsIDsSrvRequest_
{
  typedef ApriltagsIDsSrvRequest_<ContainerAllocator> Type;

  ApriltagsIDsSrvRequest_()
    {
    }
  ApriltagsIDsSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ApriltagsIDsSrvRequest_

typedef ::apriltag_finder::ApriltagsIDsSrvRequest_<std::allocator<void> > ApriltagsIDsSrvRequest;

typedef boost::shared_ptr< ::apriltag_finder::ApriltagsIDsSrvRequest > ApriltagsIDsSrvRequestPtr;
typedef boost::shared_ptr< ::apriltag_finder::ApriltagsIDsSrvRequest const> ApriltagsIDsSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace apriltag_finder

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "apriltag_finder/ApriltagsIDsSrvRequest";
  }

  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Request\n"
;
  }

  static const char* value(const ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ApriltagsIDsSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::apriltag_finder::ApriltagsIDsSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // APRILTAG_FINDER_MESSAGE_APRILTAGSIDSSRVREQUEST_H
