// Generated by gencpp from file assignment2_package/GetObjectPose.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PACKAGE_MESSAGE_GETOBJECTPOSE_H
#define ASSIGNMENT2_PACKAGE_MESSAGE_GETOBJECTPOSE_H

#include <ros/service_traits.h>


#include <assignment2_package/GetObjectPoseRequest.h>
#include <assignment2_package/GetObjectPoseResponse.h>


namespace assignment2_package
{

struct GetObjectPose
{

typedef GetObjectPoseRequest Request;
typedef GetObjectPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetObjectPose
} // namespace assignment2_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment2_package::GetObjectPose > {
  static const char* value()
  {
    return "5174181ef2b390a67f5f6f66dd09d3ff";
  }

  static const char* value(const ::assignment2_package::GetObjectPose&) { return value(); }
};

template<>
struct DataType< ::assignment2_package::GetObjectPose > {
  static const char* value()
  {
    return "assignment2_package/GetObjectPose";
  }

  static const char* value(const ::assignment2_package::GetObjectPose&) { return value(); }
};


// service_traits::MD5Sum< ::assignment2_package::GetObjectPoseRequest> should match
// service_traits::MD5Sum< ::assignment2_package::GetObjectPose >
template<>
struct MD5Sum< ::assignment2_package::GetObjectPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment2_package::GetObjectPose >::value();
  }
  static const char* value(const ::assignment2_package::GetObjectPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment2_package::GetObjectPoseRequest> should match
// service_traits::DataType< ::assignment2_package::GetObjectPose >
template<>
struct DataType< ::assignment2_package::GetObjectPoseRequest>
{
  static const char* value()
  {
    return DataType< ::assignment2_package::GetObjectPose >::value();
  }
  static const char* value(const ::assignment2_package::GetObjectPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment2_package::GetObjectPoseResponse> should match
// service_traits::MD5Sum< ::assignment2_package::GetObjectPose >
template<>
struct MD5Sum< ::assignment2_package::GetObjectPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment2_package::GetObjectPose >::value();
  }
  static const char* value(const ::assignment2_package::GetObjectPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment2_package::GetObjectPoseResponse> should match
// service_traits::DataType< ::assignment2_package::GetObjectPose >
template<>
struct DataType< ::assignment2_package::GetObjectPoseResponse>
{
  static const char* value()
  {
    return DataType< ::assignment2_package::GetObjectPose >::value();
  }
  static const char* value(const ::assignment2_package::GetObjectPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT2_PACKAGE_MESSAGE_GETOBJECTPOSE_H
