// Generated by gencpp from file assignment2_package/ObjectPose.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PACKAGE_MESSAGE_OBJECTPOSE_H
#define ASSIGNMENT2_PACKAGE_MESSAGE_OBJECTPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace assignment2_package
{
template <class ContainerAllocator>
struct ObjectPose_
{
  typedef ObjectPose_<ContainerAllocator> Type;

  ObjectPose_()
    : id(0)
    , pose()  {
    }
  ObjectPose_(const ContainerAllocator& _alloc)
    : id(0)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::assignment2_package::ObjectPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_package::ObjectPose_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectPose_

typedef ::assignment2_package::ObjectPose_<std::allocator<void> > ObjectPose;

typedef boost::shared_ptr< ::assignment2_package::ObjectPose > ObjectPosePtr;
typedef boost::shared_ptr< ::assignment2_package::ObjectPose const> ObjectPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_package::ObjectPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_package::ObjectPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_package::ObjectPose_<ContainerAllocator1> & lhs, const ::assignment2_package::ObjectPose_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.pose == rhs.pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_package::ObjectPose_<ContainerAllocator1> & lhs, const ::assignment2_package::ObjectPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::ObjectPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::ObjectPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::ObjectPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::ObjectPose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::ObjectPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::ObjectPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_package::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fad1eb37fec81628124f156f76d0e4dc";
  }

  static const char* value(const ::assignment2_package::ObjectPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfad1eb37fec81628ULL;
  static const uint64_t static_value2 = 0x124f156f76d0e4dcULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_package::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_package/ObjectPose";
  }

  static const char* value(const ::assignment2_package::ObjectPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_package::ObjectPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::assignment2_package::ObjectPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_package::ObjectPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_package::ObjectPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_package::ObjectPose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "pose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_PACKAGE_MESSAGE_OBJECTPOSE_H
