// Generated by gencpp from file assignment2_package/ObjectPoseArray.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PACKAGE_MESSAGE_OBJECTPOSEARRAY_H
#define ASSIGNMENT2_PACKAGE_MESSAGE_OBJECTPOSEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <assignment2_package/ObjectPose.h>

namespace assignment2_package
{
template <class ContainerAllocator>
struct ObjectPoseArray_
{
  typedef ObjectPoseArray_<ContainerAllocator> Type;

  ObjectPoseArray_()
    : objects()  {
    }
  ObjectPoseArray_(const ContainerAllocator& _alloc)
    : objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::assignment2_package::ObjectPose_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::assignment2_package::ObjectPose_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectPoseArray_

typedef ::assignment2_package::ObjectPoseArray_<std::allocator<void> > ObjectPoseArray;

typedef boost::shared_ptr< ::assignment2_package::ObjectPoseArray > ObjectPoseArrayPtr;
typedef boost::shared_ptr< ::assignment2_package::ObjectPoseArray const> ObjectPoseArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_package::ObjectPoseArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_package::ObjectPoseArray_<ContainerAllocator1> & lhs, const ::assignment2_package::ObjectPoseArray_<ContainerAllocator2> & rhs)
{
  return lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_package::ObjectPoseArray_<ContainerAllocator1> & lhs, const ::assignment2_package::ObjectPoseArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d14148e7c4ffcd67a5e7838038a1331";
  }

  static const char* value(const ::assignment2_package::ObjectPoseArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d14148e7c4ffcd6ULL;
  static const uint64_t static_value2 = 0x7a5e7838038a1331ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_package/ObjectPoseArray";
  }

  static const char* value(const ::assignment2_package::ObjectPoseArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_package/ObjectPose[] objects\n"
"================================================================================\n"
"MSG: assignment2_package/ObjectPose\n"
"uint32 id\n"
"geometry_msgs/PoseStamped pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::assignment2_package::ObjectPoseArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectPoseArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_package::ObjectPoseArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_package::ObjectPoseArray_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::assignment2_package::ObjectPose_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_PACKAGE_MESSAGE_OBJECTPOSEARRAY_H
