// Generated by gencpp from file assignment2_package/PickObjectResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECTRESPONSE_H
#define ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment2_package
{
template <class ContainerAllocator>
struct PickObjectResponse_
{
  typedef PickObjectResponse_<ContainerAllocator> Type;

  PickObjectResponse_()
    : success(false)  {
    }
  PickObjectResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::assignment2_package::PickObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_package::PickObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PickObjectResponse_

typedef ::assignment2_package::PickObjectResponse_<std::allocator<void> > PickObjectResponse;

typedef boost::shared_ptr< ::assignment2_package::PickObjectResponse > PickObjectResponsePtr;
typedef boost::shared_ptr< ::assignment2_package::PickObjectResponse const> PickObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_package::PickObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_package::PickObjectResponse_<ContainerAllocator1> & lhs, const ::assignment2_package::PickObjectResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_package::PickObjectResponse_<ContainerAllocator1> & lhs, const ::assignment2_package::PickObjectResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::PickObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::PickObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::PickObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::assignment2_package::PickObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_package/PickObjectResponse";
  }

  static const char* value(const ::assignment2_package::PickObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::assignment2_package::PickObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_package::PickObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_package::PickObjectResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECTRESPONSE_H
