// Generated by gencpp from file assignment2_package/PickObject.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECT_H
#define ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECT_H

#include <ros/service_traits.h>


#include <assignment2_package/PickObjectRequest.h>
#include <assignment2_package/PickObjectResponse.h>


namespace assignment2_package
{

struct PickObject
{

typedef PickObjectRequest Request;
typedef PickObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PickObject
} // namespace assignment2_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment2_package::PickObject > {
  static const char* value()
  {
    return "1353e22d17c63a0b3e01bd479f8a9f82";
  }

  static const char* value(const ::assignment2_package::PickObject&) { return value(); }
};

template<>
struct DataType< ::assignment2_package::PickObject > {
  static const char* value()
  {
    return "assignment2_package/PickObject";
  }

  static const char* value(const ::assignment2_package::PickObject&) { return value(); }
};


// service_traits::MD5Sum< ::assignment2_package::PickObjectRequest> should match
// service_traits::MD5Sum< ::assignment2_package::PickObject >
template<>
struct MD5Sum< ::assignment2_package::PickObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment2_package::PickObject >::value();
  }
  static const char* value(const ::assignment2_package::PickObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment2_package::PickObjectRequest> should match
// service_traits::DataType< ::assignment2_package::PickObject >
template<>
struct DataType< ::assignment2_package::PickObjectRequest>
{
  static const char* value()
  {
    return DataType< ::assignment2_package::PickObject >::value();
  }
  static const char* value(const ::assignment2_package::PickObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment2_package::PickObjectResponse> should match
// service_traits::MD5Sum< ::assignment2_package::PickObject >
template<>
struct MD5Sum< ::assignment2_package::PickObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment2_package::PickObject >::value();
  }
  static const char* value(const ::assignment2_package::PickObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment2_package::PickObjectResponse> should match
// service_traits::DataType< ::assignment2_package::PickObject >
template<>
struct DataType< ::assignment2_package::PickObjectResponse>
{
  static const char* value()
  {
    return DataType< ::assignment2_package::PickObject >::value();
  }
  static const char* value(const ::assignment2_package::PickObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECT_H
