// Generated by gencpp from file assignment2_package/PickObjectRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECTREQUEST_H
#define ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment2_package
{
template <class ContainerAllocator>
struct PickObjectRequest_
{
  typedef PickObjectRequest_<ContainerAllocator> Type;

  PickObjectRequest_()
    {
    }
  PickObjectRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::assignment2_package::PickObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_package::PickObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PickObjectRequest_

typedef ::assignment2_package::PickObjectRequest_<std::allocator<void> > PickObjectRequest;

typedef boost::shared_ptr< ::assignment2_package::PickObjectRequest > PickObjectRequestPtr;
typedef boost::shared_ptr< ::assignment2_package::PickObjectRequest const> PickObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_package::PickObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace assignment2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::PickObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::PickObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::PickObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::assignment2_package::PickObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_package/PickObjectRequest";
  }

  static const char* value(const ::assignment2_package::PickObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# PickObject.srv\n"
"# (Empty request)\n"
;
  }

  static const char* value(const ::assignment2_package::PickObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PickObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_package::PickObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::assignment2_package::PickObjectRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_PACKAGE_MESSAGE_PICKOBJECTREQUEST_H
