// Generated by gencpp from file assignment2_package/PlaceObject.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PACKAGE_MESSAGE_PLACEOBJECT_H
#define ASSIGNMENT2_PACKAGE_MESSAGE_PLACEOBJECT_H

#include <ros/service_traits.h>


#include <assignment2_package/PlaceObjectRequest.h>
#include <assignment2_package/PlaceObjectResponse.h>


namespace assignment2_package
{

struct PlaceObject
{

typedef PlaceObjectRequest Request;
typedef PlaceObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaceObject
} // namespace assignment2_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment2_package::PlaceObject > {
  static const char* value()
  {
    return "9a1b28e959609263fbb3c7ffb98e17db";
  }

  static const char* value(const ::assignment2_package::PlaceObject&) { return value(); }
};

template<>
struct DataType< ::assignment2_package::PlaceObject > {
  static const char* value()
  {
    return "assignment2_package/PlaceObject";
  }

  static const char* value(const ::assignment2_package::PlaceObject&) { return value(); }
};


// service_traits::MD5Sum< ::assignment2_package::PlaceObjectRequest> should match
// service_traits::MD5Sum< ::assignment2_package::PlaceObject >
template<>
struct MD5Sum< ::assignment2_package::PlaceObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment2_package::PlaceObject >::value();
  }
  static const char* value(const ::assignment2_package::PlaceObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment2_package::PlaceObjectRequest> should match
// service_traits::DataType< ::assignment2_package::PlaceObject >
template<>
struct DataType< ::assignment2_package::PlaceObjectRequest>
{
  static const char* value()
  {
    return DataType< ::assignment2_package::PlaceObject >::value();
  }
  static const char* value(const ::assignment2_package::PlaceObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment2_package::PlaceObjectResponse> should match
// service_traits::MD5Sum< ::assignment2_package::PlaceObject >
template<>
struct MD5Sum< ::assignment2_package::PlaceObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment2_package::PlaceObject >::value();
  }
  static const char* value(const ::assignment2_package::PlaceObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment2_package::PlaceObjectResponse> should match
// service_traits::DataType< ::assignment2_package::PlaceObject >
template<>
struct DataType< ::assignment2_package::PlaceObjectResponse>
{
  static const char* value()
  {
    return DataType< ::assignment2_package::PlaceObject >::value();
  }
  static const char* value(const ::assignment2_package::PlaceObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT2_PACKAGE_MESSAGE_PLACEOBJECT_H
