// Generated by gencpp from file assignment2_package/PlaceObjectRequest.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT2_PACKAGE_MESSAGE_PLACEOBJECTREQUEST_H
#define ASSIGNMENT2_PACKAGE_MESSAGE_PLACEOBJECTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment2_package
{
template <class ContainerAllocator>
struct PlaceObjectRequest_
{
  typedef PlaceObjectRequest_<ContainerAllocator> Type;

  PlaceObjectRequest_()
    : target_id(0)  {
    }
  PlaceObjectRequest_(const ContainerAllocator& _alloc)
    : target_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _target_id_type;
  _target_id_type target_id;





  typedef boost::shared_ptr< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlaceObjectRequest_

typedef ::assignment2_package::PlaceObjectRequest_<std::allocator<void> > PlaceObjectRequest;

typedef boost::shared_ptr< ::assignment2_package::PlaceObjectRequest > PlaceObjectRequestPtr;
typedef boost::shared_ptr< ::assignment2_package::PlaceObjectRequest const> PlaceObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator1> & lhs, const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator2> & rhs)
{
  return lhs.target_id == rhs.target_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator1> & lhs, const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment2_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98392fd5466c675983b3320d46c457ab";
  }

  static const char* value(const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98392fd5466c6759ULL;
  static const uint64_t static_value2 = 0x83b3320d46c457abULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment2_package/PlaceObjectRequest";
  }

  static const char* value(const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 target_id\n"
;
  }

  static const char* value(const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlaceObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment2_package::PlaceObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment2_package::PlaceObjectRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.target_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT2_PACKAGE_MESSAGE_PLACEOBJECTREQUEST_H
