waypoints:
  - { x: -0.09, y: -1.01 }     # waypoint 1
  - { x:  3.08, y:  0.00 }     # waypoint 2
  - { x:  6.58, y:  0.63 }     # waypoint 3
  - { x:  7.18, y: -0.77 }     # waypoint 4
  - { x:  8.58, y: -2.37 }     # waypoint 5
  - { x:  7.58, y: -3.37 }     # waypoint 6
  - { x:  8.88, y: -3.97 }     # waypoint 7
  - { x: 10.58, y: -4.07 }     # waypoint 8
  - { x: 11.58, y: -2.87 }     # waypoint 9
  - { x: 13.08, y: -2.87 }     # waypoint 10
  - { x: 13.08, y: -1.37 }     # waypoint 11
  - { x: 12.08, y:  1.13 }     # waypoint 12 NEEDS TO BE FIXED
  - { x: 11.08, y:  1.13 }     # waypoint 13
  - { x: 10.58, y:  0.13 }     # waypoint 14
  - { x:  8.78, y:  0.63 }     # waypoint 15
