(cl:defpackage assignment2_package-srv
  (:use )
  (:export
   "GETOBJECTPOSE"
   "<GETOBJECTPOSE-REQUEST>"
   "GETOBJECTPOSE-REQUEST"
   "<GETOBJECTPOSE-RESPONSE>"
   "GETOBJECTPOSE-RESPONSE"
   "PICKOBJECT"
   "<PICKOBJECT-REQUEST>"
   "PICKOBJECT-REQUEST"
   "<PICKOBJECT-RESPONSE>"
   "PICKOBJECT-RESPONSE"
   "PLACEOBJECT"
   "<PLACEOBJECT-REQUEST>"
   "PLACEOBJECT-REQUEST"
   "<PLACEOBJECT-RESPONSE>"
   "PLACEOBJECT-RESPONSE"
  ))

