// Generated by gencpp from file tiago_iaslab_simulation/Coeffs.msg
// DO NOT EDIT!


#ifndef TIAGO_IASLAB_SIMULATION_MESSAGE_COEFFS_H
#define TIAGO_IASLAB_SIMULATION_MESSAGE_COEFFS_H

#include <ros/service_traits.h>


#include <tiago_iaslab_simulation/CoeffsRequest.h>
#include <tiago_iaslab_simulation/CoeffsResponse.h>


namespace tiago_iaslab_simulation
{

struct Coeffs
{

typedef CoeffsRequest Request;
typedef CoeffsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Coeffs
} // namespace tiago_iaslab_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiago_iaslab_simulation::Coeffs > {
  static const char* value()
  {
    return "970e0019261c40a0b3c0c70ce65f2917";
  }

  static const char* value(const ::tiago_iaslab_simulation::Coeffs&) { return value(); }
};

template<>
struct DataType< ::tiago_iaslab_simulation::Coeffs > {
  static const char* value()
  {
    return "tiago_iaslab_simulation/Coeffs";
  }

  static const char* value(const ::tiago_iaslab_simulation::Coeffs&) { return value(); }
};


// service_traits::MD5Sum< ::tiago_iaslab_simulation::CoeffsRequest> should match
// service_traits::MD5Sum< ::tiago_iaslab_simulation::Coeffs >
template<>
struct MD5Sum< ::tiago_iaslab_simulation::CoeffsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_iaslab_simulation::Coeffs >::value();
  }
  static const char* value(const ::tiago_iaslab_simulation::CoeffsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_iaslab_simulation::CoeffsRequest> should match
// service_traits::DataType< ::tiago_iaslab_simulation::Coeffs >
template<>
struct DataType< ::tiago_iaslab_simulation::CoeffsRequest>
{
  static const char* value()
  {
    return DataType< ::tiago_iaslab_simulation::Coeffs >::value();
  }
  static const char* value(const ::tiago_iaslab_simulation::CoeffsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiago_iaslab_simulation::CoeffsResponse> should match
// service_traits::MD5Sum< ::tiago_iaslab_simulation::Coeffs >
template<>
struct MD5Sum< ::tiago_iaslab_simulation::CoeffsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_iaslab_simulation::Coeffs >::value();
  }
  static const char* value(const ::tiago_iaslab_simulation::CoeffsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_iaslab_simulation::CoeffsResponse> should match
// service_traits::DataType< ::tiago_iaslab_simulation::Coeffs >
template<>
struct DataType< ::tiago_iaslab_simulation::CoeffsResponse>
{
  static const char* value()
  {
    return DataType< ::tiago_iaslab_simulation::Coeffs >::value();
  }
  static const char* value(const ::tiago_iaslab_simulation::CoeffsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIAGO_IASLAB_SIMULATION_MESSAGE_COEFFS_H
