// Generated by gencpp from file tiago_iaslab_simulation/Objs.msg
// DO NOT EDIT!


#ifndef TIAGO_IASLAB_SIMULATION_MESSAGE_OBJS_H
#define TIAGO_IASLAB_SIMULATION_MESSAGE_OBJS_H

#include <ros/service_traits.h>


#include <tiago_iaslab_simulation/ObjsRequest.h>
#include <tiago_iaslab_simulation/ObjsResponse.h>


namespace tiago_iaslab_simulation
{

struct Objs
{

typedef ObjsRequest Request;
typedef ObjsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Objs
} // namespace tiago_iaslab_simulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tiago_iaslab_simulation::Objs > {
  static const char* value()
  {
    return "b0d667d823cb9909fa2a290df26f97da";
  }

  static const char* value(const ::tiago_iaslab_simulation::Objs&) { return value(); }
};

template<>
struct DataType< ::tiago_iaslab_simulation::Objs > {
  static const char* value()
  {
    return "tiago_iaslab_simulation/Objs";
  }

  static const char* value(const ::tiago_iaslab_simulation::Objs&) { return value(); }
};


// service_traits::MD5Sum< ::tiago_iaslab_simulation::ObjsRequest> should match
// service_traits::MD5Sum< ::tiago_iaslab_simulation::Objs >
template<>
struct MD5Sum< ::tiago_iaslab_simulation::ObjsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_iaslab_simulation::Objs >::value();
  }
  static const char* value(const ::tiago_iaslab_simulation::ObjsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_iaslab_simulation::ObjsRequest> should match
// service_traits::DataType< ::tiago_iaslab_simulation::Objs >
template<>
struct DataType< ::tiago_iaslab_simulation::ObjsRequest>
{
  static const char* value()
  {
    return DataType< ::tiago_iaslab_simulation::Objs >::value();
  }
  static const char* value(const ::tiago_iaslab_simulation::ObjsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tiago_iaslab_simulation::ObjsResponse> should match
// service_traits::MD5Sum< ::tiago_iaslab_simulation::Objs >
template<>
struct MD5Sum< ::tiago_iaslab_simulation::ObjsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tiago_iaslab_simulation::Objs >::value();
  }
  static const char* value(const ::tiago_iaslab_simulation::ObjsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tiago_iaslab_simulation::ObjsResponse> should match
// service_traits::DataType< ::tiago_iaslab_simulation::Objs >
template<>
struct DataType< ::tiago_iaslab_simulation::ObjsResponse>
{
  static const char* value()
  {
    return DataType< ::tiago_iaslab_simulation::Objs >::value();
  }
  static const char* value(const ::tiago_iaslab_simulation::ObjsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TIAGO_IASLAB_SIMULATION_MESSAGE_OBJS_H
